query AllReports(
	$skip: Int
	$take: Int
	$input: ReadReportsFilterInput!
	$filter: ReportDefinitionFilterInput
	$order: [ReportDefinitionSortInput!]
) {
	reports(skip: $skip, take: $take, input: $input, where: $filter, order: $order) {
		pageInfo {
			hasNextPage
			hasPreviousPage
		}
		totalCount
		items {
			id
			name
			description
			formDefinition
			parameters
			active
			category
		}
	}
}
